### ISSUE TITLE
卡加载界面

### ISSUE THREAD

**Issue by vi0leteve** [Avenshy/mahjong-helper-majsoul#10]
未开脚本
切换网页后可以进但是卡ui
![image](https://user-images.githubusercontent.com/117817072/213099686-bfa5a082-ef7e-4039-adc8-a1037af04689.png)
![image](https://user-images.githubusercontent.com/117817072/213099714-486c3bea-29c2-449a-811b-1803c707e0c5.png)

code.js:8051 loader callback cost a long time:803 url=res/config/lqc.lqbin
L.<computed> @ code.js:8051
s.<computed> @ code.js:8027
s.<computed> @ code.js:8007
L.<computed> @ code.js:635
F.<computed> @ code.js:499
F.<computed> @ code.js:7819
F.<computed> @ code.js:7804
Z.<computed> @ code.js:7788
load（异步）
F.send @ code.js:7787
s.load @ code.js:7876
Z.<computed> @ code.js:8311
Z.<computed> @ code.js:8285
Z.load @ code.js:8258
（匿名） @ code.js:174963
L.<computed> @ code.js:635
F.<computed> @ code.js:499
Z.<computed> @ code.js:8324
L @ code.js:8296
L.<computed> @ code.js:635
F.<computed> @ code.js:499
s.<computed> @ code.js:8033
L.<computed> @ code.js:8050
s.<computed> @ code.js:8027
s.<computed> @ code.js:8007
L.<computed> @ code.js:635
F.<computed> @ code.js:499
F.<computed> @ code.js:7819
F.<computed> @ code.js:7804
Z.<computed> @ code.js:7788
load（异步）
F.send @ code.js:7787
s.load @ code.js:7876
Z.<computed> @ code.js:8311
Z.<computed> @ code.js:8285
Z.load @ code.js:8258
y.<computed>.<computed> @ code.js:174960
（匿名） @ code.js:175148
L.<computed> @ code.js:635
F.<computed> @ code.js:499
Z.<computed> @ code.js:8324
L @ code.js:8296
L.<computed> @ code.js:635
F.<computed> @ code.js:499
s.<computed> @ code.js:8033
L.<computed> @ code.js:8050
s.<computed> @ code.js:8027
s.<computed> @ code.js:7990
M @ code.js:7899
<computed>.<computed>.<computed> @ code.js:20490
load（异步）
（匿名） @ code.js:20488
L @ code.js:20373
u.<computed> @ code.js:16585
s.<computed> @ code.js:7905
s.<computed> @ code.js:7963
L.<computed> @ code.js:635
F.<computed> @ code.js:499
F.<computed> @ code.js:7819
F.<computed> @ code.js:7804
Z.<computed> @ code.js:7788
load（异步）
F.send @ code.js:7787
s.load @ code.js:7876
Z.<computed> @ code.js:8311
Z.<computed> @ code.js:8285
Z.load @ code.js:8258
Z.<computed> @ code.js:8241
Z.<computed> @ code.js:8220
（匿名） @ code.js:175145
L.run @ code.js:624
F.<computed> @ code.js:127345
F.show @ code.js:127331
y.<computed>.<computed> @ code.js:175132
y.<computed>.<computed> @ code.js:175128
y.<computed>.<computed> @ code.js:175119
（匿名） @ code.js:174929
L.run @ code.js:624
L.<computed>.<computed> @ code.js:110890
i @ code.js:110897
（匿名） @ code.js:110909
L.run @ code.js:6295
s.<computed> @ code.js:6153
N.<computed> @ code.js:10967
N.<computed> @ code.js:10942
i @ code.js:3506
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
i @ code.js:3507
requestAnimationFrame（异步）
L @ code.js:3522
F.init @ code.js:388
y.init @ code.js:47746
y @ code.js:174641
（匿名） @ code.js:176129
The FetchEvent for "https://www.facebook.com/tr/?id=511764882872601&ev=fb_page_view&dl=https%3A%2F%2Fgame.maj-soul.com%2F1%2F&rl=&if=false&ts=1674022562262&sw=1920&sh=1080&at=" resulted in a network error response: the promise was rejected.
sw.js:1          Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:1:286
The FetchEvent for "https://www.facebook.com/tr/?id=511764882872601&ev=fb_page_view&dl=https%3A%2F%2Fgame.maj-soul.com%2F1%2F&rl=&if=false&ts=1674022603890&sw=1400&sh=1400&at=" resulted in a network error response: the promise was rejected.
Promise.then（异步）
（匿名） @ sw.js:1
sw.js:1          Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:1:286
（匿名） @ sw.js:1
www.facebook.com/tr/?id=511764882872601&ev=fb_page_view&dl=https%3A%2F%2Fgame.maj-soul.com%2F1%2F&rl=&if=false&ts=1674022603890&sw=1400&sh=1400&at=:1          GET https://www.facebook.com/tr/?id=511764882872601&ev=fb_page_view&dl=https%3A%2F%2Fgame.maj-soul.com%2F1%2F&rl=&if=false&ts=1674022603890&sw=1400&sh=1400&at= net::ERR_FAILED
Image（异步）
n @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:106
a @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:106
a @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:107
C @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:112
u @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:112
e @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:112
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:73
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:63
$U.<computed>.y.<computed>.y.<computed>.Laya.<computed>.<computed>.<computed> @ code.js:174894
a.__wrapper.a.__wrapper @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:63
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:227
setTimeout（异步）
a @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:227
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:230
j @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:24
k @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:24
n @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:24
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:230
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:231
（匿名） @ sdk.js?hash=b48a850b08ded0131e04178e696c437b:231
/1/:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
/1/:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
/1/:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
code.js:120329 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at s.<computed> [as getSegmentTaskList] (code.js:120329:45)
    at s.<computed> [as haveRedPoint] (code.js:138145:42)
    at L.<computed>.<computed> [as refreshRedpoint] (code.js:115969:117)
    at L.<computed>.<computed> [as refresh] (code.js:115934:27)
    at D.<computed>.<computed> [as refreshInfo] (code.js:116902:35)
    at D.<computed>.<computed> [as showEnter] (code.js:116875:27)
    at D.<computed>.<computed> [as onEnable] (code.js:116845:31)
    at L.<computed>.<computed> [as _onEnable] (code.js:78786:73)
    at D.set (code.js:78772:117)
    at F.<computed>.<computed> [as pending_ui_jump] (code.js:113638:63)

**Comment by becausemadoka** [comment]
遇到了同样的问题
