### ISSUE TITLE
目前发现的问题。

### ISSUE THREAD

**Issue by 17396743** [Avenshy/mahjong-helper-majsoul#15]
报错信息：
Uncaught TypeError: Cannot set properties of null (setting 'clickHandler')
    at new B (userscript.html?name=mahjong-helper-majsoul.user.js&id=b82cb506-1a18-4e4e-99ff-92d32438fb18:8160:62)
    at Z.onCreate (userscript.html?name=mahjong-helper-majsoul.user.js&id=b82cb506-1a18-4e4e-99ff-92d32438fb18:8334:50)
    at P.<computed>.<computed> [as _onload] (code.js:78790:26)
    at P.run (code.js:6292:59)
    at B.<computed> [as _update] (code.js:6150:31)
    at P.run (code.js:6292:59)
    at B.<computed> [as _update] (code.js:6148:61)
    at h.<computed> [as render] (code.js:10963:35)
    at h.<computed> [as _loop] (code.js:10938:32)
    at J (code.js:3503:35)

=============================
最后报错位置code.js：

function J() {
                m[$g[37]][$v[319]](),
                M[$v[29]][$t[354]](J);
            }

at J (code.js:3503:35)  这个位置我查了一下属性，是“onMiniGame” 。

=============================

at Z.onCreate (userscript.html?name=mahjong-helper-majsoul.user.js&id=b82cb506-1a18-4e4e-99ff-92d32438fb18:8334:50)
最后报错位置：

this["guanzhanconfig"] = new V(this.me["getChildByName"]("config"));

=============================

onMiniGame 和 guanzhanconfig 明显 不是一个属性。

我猜测就是这里出问题了。

**Comment by 17396743** [comment]
我这边简单分析了一下，是官方重新排列了code.js，需要重新解析。
